deployment:
  name: ratingsweb-deploy
  namespace: aks-workshop-dev
  labels:
    app: ratingsweb-deploy
  selectorLabels:
    app: ratingsweb-pod
  replicas: 1
  strategyType: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0
  nodeSelector:
      agentpool: aksapipool
  containers:
  - name: ratingsweb-app
    image: akswkshpacr.azurecr.io/ratings-web:v1.0.0
    imagePullPolicy: IfNotPresent    
    memoryRequest: "64Mi"
    cpuRequest: "250m"
    memoryLimit: "512Mi"
    cpuLimit: "500m"
    containerPorts: [8080]    
    env:          
    - name: API
      value: http://ratingsapi-service.aks-workshop-dev.svc
service:
  name: ratingsweb-service
  namespace: aks-workshop-dev
  selector:
    app: ratingsweb-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    
    
